#!/usr/bin/env sh

# Lua development environment to write a test XML-RPC client.

# See https://blog.papercut.com/write-xml-rpc-clients/ for more context

name=luadev
tag=1

docker image build -t $name:$tag -f - github.com/PaperCutSoftware/howto-xmlrpc-clients#:server <<'EOF'
FROM python:3.7.3-slim

COPY server.py /server.py
RUN echo 'python3 -u /server.py 2>&1 > /tmp/server.log &' >> /root/.bashrc

ARG LUA_VERSION=5.1.5
ARG ROCKS_VERSION=3.1.3

LABEL author "Alec Clews <alecclews@gmail.com>"
LABEL description "Linux with Lua and Luarocks, plus test server"

ENV DEBIAN_FRONTEND=noninteractive  
RUN apt-get update && \
    apt-get -y install build-essential libreadline-dev unzip curl ncurses-dev libexpat-dev

RUN curl http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz | \
    tar xzf - && \
    cd lua-${LUA_VERSION} && \
    make linux test && \
    make install

RUN curl https://luarocks.github.io/luarocks/releases/luarocks-${ROCKS_VERSION}.tar.gz | \
    tar xzf - && \
    cd luarocks-${ROCKS_VERSION} && \
    ./configure && \
    make build && \
    make install

RUN luarocks install luaxmlrpc

WORKDIR /work

CMD [ "/bin/bash"]
EOF

if [ $? -eq 0 ] ; then
    if uname -a | grep Microsoft ; then
        docker container run -it --rm --mount type=bind,src=$(wslpath -w $PWD),dst=/work --name myDev $name:$tag "$@"
    else
        docker container run -it --rm --mount type=bind,src=$PWD,dst=/work --name myDev $name:$tag "$@"
    fi
fi
